<%@page import="org.gocom.abframe.auth.bizlet.SkinUtil"%>
var PICTURE_ARROW_DOWN = '<%=SkinUtil.getStyleFile("images/basic/arrow_down.gif",request)%>';
var PICTURE_ARROW_RIGHT = '<%= SkinUtil.getStyleFile("images/basic/arrow_right.gif",request)%>';
var POPMENU_ARROW_RIGHT = '<%= SkinUtil.getStyleFile("images/popmenu/arrow_right.gif",request)%>';
var PICTURE_ARROW_UP = '<%= SkinUtil.getStyleFile("images/basic/arrow_up.gif",request)%>';
var PICTURE_ARROW_LEFT = '<%= SkinUtil.getStyleFile("images/basic/arrow_left.gif",request)%>';
var PICTURE_ARROW_LEFT_OVER = '<%= SkinUtil.getStyleFile("images/basic/arrow_left_over.gif",request)%>';
var PICTURE_ARROW_RIGHT_OVER = '<%= SkinUtil.getStyleFile("images/basic/arrow_right_over.gif",request)%>';
var PICTURE_CLOSE_BUTTON = '<%= SkinUtil.getStyleFile("images/calendar/close_button.gif",request)%>';
var PICTURE_BLANK = '<%= SkinUtil.getStyleFile("images/basic/blank.gif",request)%>';
var STREE_LINE_ICON='<%= SkinUtil.getStyleFile("images/tree/line.gif",request)%>';
var STREE_LEAF_ICON='<%= SkinUtil.getStyleFile("images/tree/leaf.gif",request)%>';
var STREE_FLEAF_ICON='<%= SkinUtil.getStyleFile("images/tree/FLeaf.gif",request)%>';
var STREE_LLEAF_ICON='<%= SkinUtil.getStyleFile("images/tree/LLeaf.gif",request)%>';
var STREE_MINUS_ICON='<%= SkinUtil.getStyleFile("images/tree/minus.gif",request)%>';
var STREE_LMINUS_ICON='<%= SkinUtil.getStyleFile("images/tree/LMinus.gif",request)%>';
var STREE_FMINUS_ICON='<%= SkinUtil.getStyleFile("images/tree/FMinus.gif",request)%>';
var STREE_PLUS_ICON='<%= SkinUtil.getStyleFile("images/tree/plus.gif",request)%>';
var STREE_FPLUS_ICON='<%= SkinUtil.getStyleFile("images/tree/FPlus.gif",request)%>';
var STREE_LPLUS_ICON='<%= SkinUtil.getStyleFile("images/tree/LPlus.gif",request)%>';
var RTREE_DROP_YES='<%= SkinUtil.getStyleFile("images/tree/drop-yes.gif",request)%>';
var RTREE_DROP_NO='<%= SkinUtil.getStyleFile("images/tree/drop-no.gif",request)%>';
var RTREE_DROP_LOADING='<%= SkinUtil.getStyleFile("images/tree/loading.gif",request)%>';
var STREE_DEFAULTOPEN_ICON='<%= SkinUtil.getStyleFile("images/tree/defaultOpen.png",request)%>';
var STREE_DEFAULTCLOSE_ICON='<%= SkinUtil.getStyleFile("images/tree/defaultClose.png",request)%>';
var STREE_ROOTPLUS_ICON='<%= SkinUtil.getStyleFile("images/tree/rootPlus.gif",request)%>';
var STREE_ROOTMINUS_ICON='<%= SkinUtil.getStyleFile("images/tree/rootMinus.gif",request)%>';
var STREE_BLANK_ICON='<%= SkinUtil.getStyleFile("images/tree/treeBlank.gif",request)%>';
var STREE_CHECKBOX_TRUE_ICON='<%= SkinUtil.getStyleFile("images/basic/checkbox_true.gif",request)%>';
var STREE_CHECKBOX_FALSE_ICON='<%= SkinUtil.getStyleFile("images/basic/checkbox_false.gif",request)%>';
var STREE_CHECKBOX_TRUE_ICON1='<%= SkinUtil.getStyleFile("images/basic/checkbox_true1.gif",request)%>';
var GROUPPANEL_CLOSE = '<%= SkinUtil.getStyleFile("images/grouppanel/grouppanel_close.gif",request)%>';
var GROUPPANEL_OPEN = '<%= SkinUtil.getStyleFile("images/grouppanel/grouppanel_open.gif",request)%>';
